// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"time"

	"github.com/jadams-positron/acai-sh-server/internal/domain/events"
)

// recentActivity renders the "Recent activity" strip used on team /
// product / impl pages. Hidden entirely when the slice is empty so the
// section doesn't show as a blank panel.
func recentActivity(es []*events.Event) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(es) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"panel recent-activity\"><header style=\"display: flex; align-items: baseline; justify-content: space-between; margin-bottom: var(--space-md);\"><h2 style=\"font-size: var(--text-xl); margin: 0;\">Recent activity</h2><span class=\"subtitle\" style=\"font-size: var(--text-xs); text-transform: uppercase; letter-spacing: 0.18em;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(pluralize(len(es), "event"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 19, Col: 34}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></header><ul class=\"recent-activity-list\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, e := range es {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"recent-activity-row\"><span class=\"recent-activity-actor\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(formatActor(e))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 25, Col: 58}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(" ")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 26, Col: 11}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " <span class=\"recent-activity-verb\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(formatVerb(e))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 27, Col: 56}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span> <span class=\"recent-activity-time\" title=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(e.InsertedAt.Format(time.RFC3339))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 28, Col: 82}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(formatRelative(e.InsertedAt))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/views/recent_activity.templ`, Line: 29, Col: 37}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span></li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</ul></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// formatActor returns a short label for the event's actor — either the
// user's email local part, or "system" for unattributed events.
func formatActor(e *events.Event) string {
	if e.ActorEmail == nil || *e.ActorEmail == "" {
		return "system"
	}
	email := *e.ActorEmail
	if idx := indexAt(email); idx > 0 {
		return email[:idx]
	}
	return email
}

// indexAt returns the index of the '@' character or -1.
func indexAt(s string) int {
	for i := 0; i < len(s); i++ {
		if s[i] == '@' {
			return i
		}
	}
	return -1
}

// formatVerb composes the human-readable middle of an activity row from
// the event kind + payload. Kept conservative: we never panic on
// missing payload fields, falling back to a generic phrase.
func formatVerb(e *events.Event) string {
	switch e.Kind {
	case events.KindPushSpec:
		feat := payloadString(e.Payload, "feature_name")
		branch := payloadString(e.Payload, "branch")
		if feat != "" && branch != "" {
			return fmt.Sprintf("pushed spec for %s on %s", feat, branch)
		}
		if feat != "" {
			return "pushed spec for " + feat
		}
		return "pushed a spec"
	case events.KindPushRefs:
		feat := payloadString(e.Payload, "feature_name")
		count, _ := e.Payload["ref_count"].(float64)
		if feat != "" && count > 0 {
			return fmt.Sprintf("pushed %d refs to %s", int(count), feat)
		}
		if feat != "" {
			return "pushed refs to " + feat
		}
		return "pushed refs"
	case events.KindStatusChanged:
		acid := payloadString(e.Payload, "acid")
		to := payloadString(e.Payload, "to")
		feat := ""
		if e.FeatureName != nil {
			feat = *e.FeatureName
		}
		switch {
		case acid != "" && to != "" && feat != "":
			return fmt.Sprintf("set %s on %s → %s", acid, feat, to)
		case acid != "" && to != "":
			return fmt.Sprintf("set %s → %s", acid, to)
		case acid != "":
			return "cleared " + acid
		default:
			return "updated a status"
		}
	case events.KindTokenMinted:
		name := payloadString(e.Payload, "token_name")
		if name != "" {
			return "minted token " + name
		}
		return "minted a token"
	case events.KindMemberAdded:
		role := payloadString(e.Payload, "role")
		if role != "" {
			return "added a member as " + role
		}
		return "added a member"
	case events.KindProductCreated:
		name := payloadString(e.Payload, "product_name")
		if name != "" {
			return "created product " + name
		}
		return "created a product"
	case events.KindImplCreated:
		name := payloadString(e.Payload, "impl_name")
		if name != "" {
			return "created impl " + name
		}
		return "created an implementation"
	default:
		return e.Kind
	}
}

// payloadString safely projects a string field from the JSON payload map.
func payloadString(m map[string]any, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

// formatRelative returns a short "Xm ago" / "Xh ago" / "Xd ago" string.
// Falls through to an absolute date for events older than ~1 month.
func formatRelative(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	d := time.Since(t)
	switch {
	case d < 30*time.Second:
		return "just now"
	case d < time.Minute:
		return fmt.Sprintf("%ds ago", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm ago", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh ago", int(d.Hours()))
	case d < 30*24*time.Hour:
		return fmt.Sprintf("%dd ago", int(d.Hours()/24))
	default:
		return t.Format("2006-01-02")
	}
}

var _ = templruntime.GeneratedTemplate
