defmodule Acai.Implementations.TrackedBranchTest do
  use Acai.DataCase, async: true

  import Acai.DataModelFixtures

  alias Acai.Implementations.TrackedBranch

  @valid_attrs %{
    repo_uri: "github.com/jadams-positron/acai-sh-server"
  }

  describe "changeset/2" do
    test "valid with required fields" do
      team = team_fixture()
      product = product_fixture(team)
      impl = implementation_fixture(product)
      branch = branch_fixture()

      attrs =
        @valid_attrs
        |> Map.put(:implementation_id, impl.id)
        |> Map.put(:branch_id, branch.id)

      cs = TrackedBranch.changeset(%TrackedBranch{}, attrs)
      assert cs.valid?
    end

    # data-model.TRACKED_BRANCHES.1
    # data-model.TRACKED_BRANCHES.2
    # data-model.TRACKED_BRANCHES.5
    test "invalid without required fields" do
      cs = TrackedBranch.changeset(%TrackedBranch{}, %{})
      refute cs.valid?
      assert %{repo_uri: [_ | _]} = errors_on(cs)
      assert %{implementation_id: [_ | _]} = errors_on(cs)
      assert %{branch_id: [_ | _]} = errors_on(cs)
    end

    # data-model.TRACKED_BRANCHES.3
    test "uses composite primary key" do
      # With @primary_key false, the schema has no autogenerated id
      assert TrackedBranch.__schema__(:primary_key) == [:implementation_id, :branch_id]
    end
  end

  describe "database constraints" do
    # data-model.TRACKED_BRANCHES.4
    test "composite unique constraint on (implementation_id, repo_uri)" do
      team = team_fixture()
      product = product_fixture(team)
      impl = implementation_fixture(product)
      branch1 = branch_fixture(%{repo_uri: "github.com/jadams-positron/acai-sh-server"})
      branch2 = branch_fixture(%{repo_uri: "github.com/jadams-positron/acai-sh-server", branch_name: "develop"})

      # First tracked branch should succeed
      tracked_branch_fixture(impl, %{branch: branch1, repo_uri: "github.com/jadams-positron/acai-sh-server"})

      # Second tracked branch with same implementation and repo_uri should fail
      attrs =
        @valid_attrs
        |> Map.put(:implementation_id, impl.id)
        |> Map.put(:branch_id, branch2.id)
        |> Map.put(:repo_uri, "github.com/jadams-positron/acai-sh-server")

      {:error, cs} =
        TrackedBranch.changeset(%TrackedBranch{}, attrs)
        |> Acai.Repo.insert()

      assert %{implementation_id: [_ | _]} = errors_on(cs)
    end
  end
end
