// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package sqlc

import (
	"context"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (
  id, user_id, team_id, name, token_hash, token_prefix,
  scopes, expires_at, revoked_at, last_used_at, inserted_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, team_id, name, token_hash, token_prefix, scopes, expires_at, revoked_at, last_used_at, inserted_at, updated_at
`

type CreateAccessTokenParams struct {
	ID          string
	UserID      string
	TeamID      string
	Name        string
	TokenHash   string
	TokenPrefix string
	Scopes      string
	ExpiresAt   *string
	RevokedAt   *string
	LastUsedAt  *string
	InsertedAt  string
	UpdatedAt   string
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, createAccessToken,
		arg.ID,
		arg.UserID,
		arg.TeamID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.LastUsedAt,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessTokenByPrefix = `-- name: GetAccessTokenByPrefix :one
SELECT id, user_id, team_id, name, token_hash, token_prefix, scopes, expires_at, revoked_at, last_used_at, inserted_at, updated_at
FROM access_tokens
WHERE token_prefix = ?
LIMIT 1
`

func (q *Queries) GetAccessTokenByPrefix(ctx context.Context, tokenPrefix string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByPrefix, tokenPrefix)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens
SET revoked_at = ?, updated_at = ?
WHERE id = ?
`

type RevokeAccessTokenParams struct {
	RevokedAt *string
	UpdatedAt string
	ID        string
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeAccessToken, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateAccessTokenLastUsed = `-- name: UpdateAccessTokenLastUsed :exec
UPDATE access_tokens
SET last_used_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateAccessTokenLastUsedParams struct {
	LastUsedAt *string
	UpdatedAt  string
	ID         string
}

func (q *Queries) UpdateAccessTokenLastUsed(ctx context.Context, arg UpdateAccessTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAccessTokenLastUsed, arg.LastUsedAt, arg.UpdatedAt, arg.ID)
	return err
}
