// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
  id, team_id, product_id, impl_id, feature_name, actor_user_id,
  kind, payload, inserted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID          string
	TeamID      string
	ProductID   *string
	ImplID      *string
	FeatureName *string
	ActorUserID *string
	Kind        string
	Payload     string
	InsertedAt  string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.TeamID,
		arg.ProductID,
		arg.ImplID,
		arg.FeatureName,
		arg.ActorUserID,
		arg.Kind,
		arg.Payload,
		arg.InsertedAt,
	)
	return err
}

const listEventsForImpl = `-- name: ListEventsForImpl :many
SELECT e.id, e.team_id, e.product_id, e.impl_id, e.feature_name,
       e.actor_user_id, e.kind, e.payload, e.inserted_at,
       u.email AS actor_email
FROM events e
LEFT JOIN users u ON u.id = e.actor_user_id
WHERE e.impl_id = ?
ORDER BY e.inserted_at DESC
LIMIT ?
`

type ListEventsForImplParams struct {
	ImplID *string
	Limit  int64
}

type ListEventsForImplRow struct {
	ID          string
	TeamID      string
	ProductID   *string
	ImplID      *string
	FeatureName *string
	ActorUserID *string
	Kind        string
	Payload     string
	InsertedAt  string
	ActorEmail  *string
}

func (q *Queries) ListEventsForImpl(ctx context.Context, arg ListEventsForImplParams) ([]ListEventsForImplRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForImpl, arg.ImplID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForImplRow{}
	for rows.Next() {
		var i ListEventsForImplRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProductID,
			&i.ImplID,
			&i.FeatureName,
			&i.ActorUserID,
			&i.Kind,
			&i.Payload,
			&i.InsertedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForProduct = `-- name: ListEventsForProduct :many
SELECT e.id, e.team_id, e.product_id, e.impl_id, e.feature_name,
       e.actor_user_id, e.kind, e.payload, e.inserted_at,
       u.email AS actor_email
FROM events e
LEFT JOIN users u ON u.id = e.actor_user_id
WHERE e.product_id = ?
ORDER BY e.inserted_at DESC
LIMIT ?
`

type ListEventsForProductParams struct {
	ProductID *string
	Limit     int64
}

type ListEventsForProductRow struct {
	ID          string
	TeamID      string
	ProductID   *string
	ImplID      *string
	FeatureName *string
	ActorUserID *string
	Kind        string
	Payload     string
	InsertedAt  string
	ActorEmail  *string
}

func (q *Queries) ListEventsForProduct(ctx context.Context, arg ListEventsForProductParams) ([]ListEventsForProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForProduct, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForProductRow{}
	for rows.Next() {
		var i ListEventsForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProductID,
			&i.ImplID,
			&i.FeatureName,
			&i.ActorUserID,
			&i.Kind,
			&i.Payload,
			&i.InsertedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForTeam = `-- name: ListEventsForTeam :many
SELECT e.id, e.team_id, e.product_id, e.impl_id, e.feature_name,
       e.actor_user_id, e.kind, e.payload, e.inserted_at,
       u.email AS actor_email
FROM events e
LEFT JOIN users u ON u.id = e.actor_user_id
WHERE e.team_id = ?
ORDER BY e.inserted_at DESC
LIMIT ?
`

type ListEventsForTeamParams struct {
	TeamID string
	Limit  int64
}

type ListEventsForTeamRow struct {
	ID          string
	TeamID      string
	ProductID   *string
	ImplID      *string
	FeatureName *string
	ActorUserID *string
	Kind        string
	Payload     string
	InsertedAt  string
	ActorEmail  *string
}

func (q *Queries) ListEventsForTeam(ctx context.Context, arg ListEventsForTeamParams) ([]ListEventsForTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForTeamRow{}
	for rows.Next() {
		var i ListEventsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProductID,
			&i.ImplID,
			&i.FeatureName,
			&i.ActorUserID,
			&i.Kind,
			&i.Payload,
			&i.InsertedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
