// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: implementations.sql

package sqlc

import (
	"context"
)

const createImplementation = `-- name: CreateImplementation :one
INSERT INTO implementations (id, product_id, team_id, parent_implementation_id, name, is_active, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id, product_id, team_id, parent_implementation_id, name, description, is_active, inserted_at, updated_at
`

type CreateImplementationParams struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	InsertedAt             string
	UpdatedAt              string
}

func (q *Queries) CreateImplementation(ctx context.Context, arg CreateImplementationParams) (Implementation, error) {
	row := q.db.QueryRowContext(ctx, createImplementation,
		arg.ID,
		arg.ProductID,
		arg.TeamID,
		arg.ParentImplementationID,
		arg.Name,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Implementation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TeamID,
		&i.ParentImplementationID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImplementationsByBranch = `-- name: ListImplementationsByBranch :many
SELECT DISTINCT i.id, i.product_id, i.team_id, i.parent_implementation_id,
                i.name, i.description, i.is_active, i.inserted_at, i.updated_at,
                p.name AS product_name
FROM implementations i
JOIN products p ON p.id = i.product_id
JOIN tracked_branches tb ON tb.implementation_id = i.id
JOIN branches b ON b.id = tb.branch_id
WHERE i.team_id = ?
  AND i.is_active = 1
  AND b.repo_uri = ?
  AND b.branch_name = ?
ORDER BY p.name, i.name
`

type ListImplementationsByBranchParams struct {
	TeamID     string
	RepoUri    string
	BranchName string
}

type ListImplementationsByBranchRow struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
	ProductName            string
}

func (q *Queries) ListImplementationsByBranch(ctx context.Context, arg ListImplementationsByBranchParams) ([]ListImplementationsByBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationsByBranch, arg.TeamID, arg.RepoUri, arg.BranchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsByBranchRow{}
	for rows.Next() {
		var i ListImplementationsByBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TeamID,
			&i.ParentImplementationID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationsByProduct = `-- name: ListImplementationsByProduct :many
SELECT i.id, i.product_id, i.team_id, i.parent_implementation_id,
       i.name, i.description, i.is_active, i.inserted_at, i.updated_at,
       p.name AS product_name
FROM implementations i
JOIN products p ON p.id = i.product_id
WHERE i.team_id = ?
  AND i.product_id = ?
  AND i.is_active = 1
ORDER BY i.name
`

type ListImplementationsByProductParams struct {
	TeamID    string
	ProductID string
}

type ListImplementationsByProductRow struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
	ProductName            string
}

func (q *Queries) ListImplementationsByProduct(ctx context.Context, arg ListImplementationsByProductParams) ([]ListImplementationsByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationsByProduct, arg.TeamID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsByProductRow{}
	for rows.Next() {
		var i ListImplementationsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TeamID,
			&i.ParentImplementationID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationsByProductAndBranch = `-- name: ListImplementationsByProductAndBranch :many
SELECT DISTINCT i.id, i.product_id, i.team_id, i.parent_implementation_id,
                i.name, i.description, i.is_active, i.inserted_at, i.updated_at,
                p.name AS product_name
FROM implementations i
JOIN products p ON p.id = i.product_id
JOIN tracked_branches tb ON tb.implementation_id = i.id
JOIN branches b ON b.id = tb.branch_id
WHERE i.team_id = ?
  AND i.product_id = ?
  AND i.is_active = 1
  AND b.repo_uri = ?
  AND b.branch_name = ?
ORDER BY i.name
`

type ListImplementationsByProductAndBranchParams struct {
	TeamID     string
	ProductID  string
	RepoUri    string
	BranchName string
}

type ListImplementationsByProductAndBranchRow struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
	ProductName            string
}

func (q *Queries) ListImplementationsByProductAndBranch(ctx context.Context, arg ListImplementationsByProductAndBranchParams) ([]ListImplementationsByProductAndBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationsByProductAndBranch,
		arg.TeamID,
		arg.ProductID,
		arg.RepoUri,
		arg.BranchName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsByProductAndBranchRow{}
	for rows.Next() {
		var i ListImplementationsByProductAndBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TeamID,
			&i.ParentImplementationID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationsByTeam = `-- name: ListImplementationsByTeam :many
SELECT i.id, i.product_id, i.team_id, i.parent_implementation_id,
       i.name, i.description, i.is_active, i.inserted_at, i.updated_at,
       p.name AS product_name
FROM implementations i
JOIN products p ON p.id = i.product_id
WHERE i.team_id = ?
  AND i.is_active = 1
ORDER BY p.name, i.name
`

type ListImplementationsByTeamRow struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
	ProductName            string
}

func (q *Queries) ListImplementationsByTeam(ctx context.Context, teamID string) ([]ListImplementationsByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsByTeamRow{}
	for rows.Next() {
		var i ListImplementationsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TeamID,
			&i.ParentImplementationID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationsTrackingBranch = `-- name: ListImplementationsTrackingBranch :many
SELECT i.id, i.product_id, i.team_id, i.parent_implementation_id,
       i.name, i.description, i.is_active, i.inserted_at, i.updated_at,
       p.name AS product_name
FROM implementations i
JOIN products p ON p.id = i.product_id
JOIN tracked_branches tb ON tb.implementation_id = i.id
WHERE i.team_id = ?
  AND tb.branch_id = ?
  AND i.is_active = 1
ORDER BY i.name
`

type ListImplementationsTrackingBranchParams struct {
	TeamID   string
	BranchID string
}

type ListImplementationsTrackingBranchRow struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
	ProductName            string
}

func (q *Queries) ListImplementationsTrackingBranch(ctx context.Context, arg ListImplementationsTrackingBranchParams) ([]ListImplementationsTrackingBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, listImplementationsTrackingBranch, arg.TeamID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsTrackingBranchRow{}
	for rows.Next() {
		var i ListImplementationsTrackingBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.TeamID,
			&i.ParentImplementationID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
