// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AccessToken struct {
	ID          string
	UserID      string
	TeamID      string
	Name        string
	TokenHash   string
	TokenPrefix string
	Scopes      string
	ExpiresAt   *string
	RevokedAt   *string
	LastUsedAt  *string
	InsertedAt  string
	UpdatedAt   string
}

type Branch struct {
	ID             string
	TeamID         string
	RepoUri        string
	BranchName     string
	LastSeenCommit string
	InsertedAt     string
	UpdatedAt      string
}

type EmailToken struct {
	ID         string
	UserID     string
	TokenHash  []byte
	Context    string
	SentTo     string
	InsertedAt string
}

type FeatureBranchRef struct {
	ID          string
	BranchID    string
	FeatureName string
	Refs        string
	Commit      string
	PushedAt    string
	InsertedAt  string
	UpdatedAt   string
}

type FeatureImplState struct {
	ID               string
	ImplementationID string
	FeatureName      string
	States           string
	InsertedAt       string
	UpdatedAt        string
}

type Implementation struct {
	ID                     string
	ProductID              string
	TeamID                 string
	ParentImplementationID *string
	Name                   string
	Description            *string
	IsActive               int64
	InsertedAt             string
	UpdatedAt              string
}

type Product struct {
	ID          string
	TeamID      string
	Name        string
	Description *string
	IsActive    int64
	InsertedAt  string
	UpdatedAt   string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Spec struct {
	ID                 string
	ProductID          string
	BranchID           string
	Path               *string
	LastSeenCommit     string
	ParsedAt           string
	FeatureName        string
	FeatureDescription *string
	FeatureVersion     string
	RawContent         *string
	Requirements       string
	InsertedAt         string
	UpdatedAt          string
}

type Team struct {
	ID          string
	Name        string
	GlobalAdmin int64
	InsertedAt  string
	UpdatedAt   string
}

type TrackedBranch struct {
	ImplementationID string
	BranchID         string
	RepoUri          string
	InsertedAt       string
	UpdatedAt        string
}

type User struct {
	ID             string
	Email          string
	HashedPassword *string
	ConfirmedAt    *string
	InsertedAt     string
	UpdatedAt      string
}

type UserTeamRole struct {
	TeamID     string
	UserID     string
	Title      string
	InsertedAt string
	UpdatedAt  string
}
