// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, team_id, name, is_active, inserted_at, updated_at)
VALUES (?, ?, ?, 1, ?, ?)
RETURNING id, team_id, name, description, is_active, inserted_at, updated_at
`

type CreateProductParams struct {
	ID         string
	TeamID     string
	Name       string
	InsertedAt string
	UpdatedAt  string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByTeamAndName = `-- name: GetProductByTeamAndName :one
SELECT id, team_id, name, description, is_active, inserted_at, updated_at
FROM products
WHERE team_id = ?
  AND name = ? COLLATE NOCASE
LIMIT 1
`

type GetProductByTeamAndNameParams struct {
	TeamID string
	Name   string
}

func (q *Queries) GetProductByTeamAndName(ctx context.Context, arg GetProductByTeamAndNameParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByTeamAndName, arg.TeamID, arg.Name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsForTeam = `-- name: ListProductsForTeam :many
SELECT id, team_id, name, description, is_active, inserted_at, updated_at
FROM products
WHERE team_id = ?
  AND is_active = 1
ORDER BY name
`

func (q *Queries) ListProductsForTeam(ctx context.Context, teamID string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
