// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
)

const getProductByTeamAndName = `-- name: GetProductByTeamAndName :one
SELECT id, team_id, name, description, is_active, inserted_at, updated_at
FROM products
WHERE team_id = ?
  AND name = ? COLLATE NOCASE
LIMIT 1
`

type GetProductByTeamAndNameParams struct {
	TeamID string
	Name   string
}

func (q *Queries) GetProductByTeamAndName(ctx context.Context, arg GetProductByTeamAndNameParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByTeamAndName, arg.TeamID, arg.Name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
