// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Ping returns 1 if the DB is reachable. Used by /_health.
	Ping(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
