// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specs.sql

package sqlc

import (
	"context"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (id, team_id, repo_uri, branch_name, last_seen_commit, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, team_id, repo_uri, branch_name, last_seen_commit, inserted_at, updated_at
`

type CreateBranchParams struct {
	ID             string
	TeamID         string
	RepoUri        string
	BranchName     string
	LastSeenCommit string
	InsertedAt     string
	UpdatedAt      string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, createBranch,
		arg.ID,
		arg.TeamID,
		arg.RepoUri,
		arg.BranchName,
		arg.LastSeenCommit,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RepoUri,
		&i.BranchName,
		&i.LastSeenCommit,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchByTeamRepoAndName = `-- name: GetBranchByTeamRepoAndName :one
SELECT id, team_id, repo_uri, branch_name, last_seen_commit, inserted_at, updated_at
FROM branches
WHERE team_id = ? AND repo_uri = ? AND branch_name = ?
LIMIT 1
`

type GetBranchByTeamRepoAndNameParams struct {
	TeamID     string
	RepoUri    string
	BranchName string
}

func (q *Queries) GetBranchByTeamRepoAndName(ctx context.Context, arg GetBranchByTeamRepoAndNameParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getBranchByTeamRepoAndName, arg.TeamID, arg.RepoUri, arg.BranchName)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RepoUri,
		&i.BranchName,
		&i.LastSeenCommit,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureBranchRef = `-- name: GetFeatureBranchRef :one
SELECT id, branch_id, feature_name, refs, "commit", pushed_at, inserted_at, updated_at
FROM feature_branch_refs
WHERE branch_id = ?
  AND feature_name = ?
LIMIT 1
`

type GetFeatureBranchRefParams struct {
	BranchID    string
	FeatureName string
}

func (q *Queries) GetFeatureBranchRef(ctx context.Context, arg GetFeatureBranchRefParams) (FeatureBranchRef, error) {
	row := q.db.QueryRowContext(ctx, getFeatureBranchRef, arg.BranchID, arg.FeatureName)
	var i FeatureBranchRef
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.FeatureName,
		&i.Refs,
		&i.Commit,
		&i.PushedAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureImplState = `-- name: GetFeatureImplState :one
SELECT id, implementation_id, feature_name, states, inserted_at, updated_at
FROM feature_impl_states
WHERE implementation_id = ?
  AND feature_name = ?
LIMIT 1
`

type GetFeatureImplStateParams struct {
	ImplementationID string
	FeatureName      string
}

func (q *Queries) GetFeatureImplState(ctx context.Context, arg GetFeatureImplStateParams) (FeatureImplState, error) {
	row := q.db.QueryRowContext(ctx, getFeatureImplState, arg.ImplementationID, arg.FeatureName)
	var i FeatureImplState
	err := row.Scan(
		&i.ID,
		&i.ImplementationID,
		&i.FeatureName,
		&i.States,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImplementationByProductAndName = `-- name: GetImplementationByProductAndName :one
SELECT id, product_id, team_id, parent_implementation_id, name, description, is_active, inserted_at, updated_at
FROM implementations
WHERE product_id = ?
  AND name = ?
  AND is_active = 1
LIMIT 1
`

type GetImplementationByProductAndNameParams struct {
	ProductID string
	Name      string
}

func (q *Queries) GetImplementationByProductAndName(ctx context.Context, arg GetImplementationByProductAndNameParams) (Implementation, error) {
	row := q.db.QueryRowContext(ctx, getImplementationByProductAndName, arg.ProductID, arg.Name)
	var i Implementation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TeamID,
		&i.ParentImplementationID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpecByBranchAndFeature = `-- name: GetSpecByBranchAndFeature :one
SELECT id, product_id, branch_id, path, last_seen_commit, parsed_at, feature_name, feature_description, feature_version, raw_content, requirements, inserted_at, updated_at
FROM specs
WHERE branch_id = ?
  AND feature_name = ?
LIMIT 1
`

type GetSpecByBranchAndFeatureParams struct {
	BranchID    string
	FeatureName string
}

func (q *Queries) GetSpecByBranchAndFeature(ctx context.Context, arg GetSpecByBranchAndFeatureParams) (Spec, error) {
	row := q.db.QueryRowContext(ctx, getSpecByBranchAndFeature, arg.BranchID, arg.FeatureName)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Path,
		&i.LastSeenCommit,
		&i.ParsedAt,
		&i.FeatureName,
		&i.FeatureDescription,
		&i.FeatureVersion,
		&i.RawContent,
		&i.Requirements,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchesForImplementation = `-- name: ListBranchesForImplementation :many
SELECT b.id, b.team_id, b.repo_uri, b.branch_name, b.last_seen_commit, b.inserted_at, b.updated_at
FROM branches b
JOIN tracked_branches tb ON tb.branch_id = b.id
WHERE tb.implementation_id = ?
ORDER BY b.updated_at DESC
`

func (q *Queries) ListBranchesForImplementation(ctx context.Context, implementationID string) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listBranchesForImplementation, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RepoUri,
			&i.BranchName,
			&i.LastSeenCommit,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureBranchRefsForBranch = `-- name: ListFeatureBranchRefsForBranch :many
SELECT id, branch_id, feature_name, refs, "commit", pushed_at, inserted_at, updated_at
FROM feature_branch_refs
WHERE branch_id = ?
ORDER BY feature_name
`

func (q *Queries) ListFeatureBranchRefsForBranch(ctx context.Context, branchID string) ([]FeatureBranchRef, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureBranchRefsForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureBranchRef{}
	for rows.Next() {
		var i FeatureBranchRef
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.FeatureName,
			&i.Refs,
			&i.Commit,
			&i.PushedAt,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureImplStatesForImpl = `-- name: ListFeatureImplStatesForImpl :many
SELECT id, implementation_id, feature_name, states, inserted_at, updated_at
FROM feature_impl_states
WHERE implementation_id = ?
ORDER BY feature_name
`

func (q *Queries) ListFeatureImplStatesForImpl(ctx context.Context, implementationID string) ([]FeatureImplState, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureImplStatesForImpl, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureImplState{}
	for rows.Next() {
		var i FeatureImplState
		if err := rows.Scan(
			&i.ID,
			&i.ImplementationID,
			&i.FeatureName,
			&i.States,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecsForBranch = `-- name: ListSpecsForBranch :many
SELECT id, product_id, branch_id, path, last_seen_commit, parsed_at, feature_name, feature_description, feature_version, raw_content, requirements, inserted_at, updated_at
FROM specs
WHERE branch_id = ?
ORDER BY feature_name
`

func (q *Queries) ListSpecsForBranch(ctx context.Context, branchID string) ([]Spec, error) {
	rows, err := q.db.QueryContext(ctx, listSpecsForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spec{}
	for rows.Next() {
		var i Spec
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.Path,
			&i.LastSeenCommit,
			&i.ParsedAt,
			&i.FeatureName,
			&i.FeatureDescription,
			&i.FeatureVersion,
			&i.RawContent,
			&i.Requirements,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickRefsBranchForFeature = `-- name: PickRefsBranchForFeature :one
SELECT b.id, b.team_id, b.repo_uri, b.branch_name, b.last_seen_commit, b.inserted_at, b.updated_at
FROM branches b
JOIN tracked_branches tb ON tb.branch_id = b.id
JOIN feature_branch_refs fbr ON fbr.branch_id = b.id AND fbr.feature_name = ?
WHERE tb.implementation_id = ?
ORDER BY fbr.pushed_at DESC
LIMIT 1
`

type PickRefsBranchForFeatureParams struct {
	FeatureName      string
	ImplementationID string
}

// Of the impl's tracked branches, return the branch with the most-recent
// feature_branch_refs.pushed_at for the given feature_name. Used as the
// "refs_source" branch when we have multiple tracked branches.
func (q *Queries) PickRefsBranchForFeature(ctx context.Context, arg PickRefsBranchForFeatureParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, pickRefsBranchForFeature, arg.FeatureName, arg.ImplementationID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RepoUri,
		&i.BranchName,
		&i.LastSeenCommit,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBranchLastSeenCommit = `-- name: UpdateBranchLastSeenCommit :exec
UPDATE branches
SET last_seen_commit = ?, updated_at = ?
WHERE id = ?
`

type UpdateBranchLastSeenCommitParams struct {
	LastSeenCommit string
	UpdatedAt      string
	ID             string
}

func (q *Queries) UpdateBranchLastSeenCommit(ctx context.Context, arg UpdateBranchLastSeenCommitParams) error {
	_, err := q.db.ExecContext(ctx, updateBranchLastSeenCommit, arg.LastSeenCommit, arg.UpdatedAt, arg.ID)
	return err
}

const upsertFeatureBranchRef = `-- name: UpsertFeatureBranchRef :exec
INSERT INTO feature_branch_refs (
  id, branch_id, feature_name, refs, "commit", pushed_at, inserted_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(branch_id, feature_name) DO UPDATE
SET refs = excluded.refs,
    "commit" = excluded."commit",
    pushed_at = excluded.pushed_at,
    updated_at = excluded.updated_at
`

type UpsertFeatureBranchRefParams struct {
	ID          string
	BranchID    string
	FeatureName string
	Refs        string
	Commit      string
	PushedAt    string
	InsertedAt  string
	UpdatedAt   string
}

func (q *Queries) UpsertFeatureBranchRef(ctx context.Context, arg UpsertFeatureBranchRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeatureBranchRef,
		arg.ID,
		arg.BranchID,
		arg.FeatureName,
		arg.Refs,
		arg.Commit,
		arg.PushedAt,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertFeatureImplState = `-- name: UpsertFeatureImplState :exec
INSERT INTO feature_impl_states (id, implementation_id, feature_name, states, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(implementation_id, feature_name) DO UPDATE
SET states = excluded.states,
    updated_at = excluded.updated_at
`

type UpsertFeatureImplStateParams struct {
	ID               string
	ImplementationID string
	FeatureName      string
	States           string
	InsertedAt       string
	UpdatedAt        string
}

// Upserts the row for (implementation_id, feature_name) with the given states JSON.
// Insert if missing, update otherwise.
func (q *Queries) UpsertFeatureImplState(ctx context.Context, arg UpsertFeatureImplStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeatureImplState,
		arg.ID,
		arg.ImplementationID,
		arg.FeatureName,
		arg.States,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertSpec = `-- name: UpsertSpec :one
INSERT INTO specs (
  id, product_id, branch_id, path, last_seen_commit, parsed_at,
  feature_name, feature_description, feature_version, raw_content, requirements,
  inserted_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(branch_id, feature_name) DO UPDATE
SET path = excluded.path,
    last_seen_commit = excluded.last_seen_commit,
    parsed_at = excluded.parsed_at,
    feature_description = excluded.feature_description,
    feature_version = excluded.feature_version,
    raw_content = excluded.raw_content,
    requirements = excluded.requirements,
    updated_at = excluded.updated_at
RETURNING id, product_id, branch_id, path, last_seen_commit, parsed_at, feature_name, feature_description, feature_version, raw_content, requirements, inserted_at, updated_at
`

type UpsertSpecParams struct {
	ID                 string
	ProductID          string
	BranchID           string
	Path               *string
	LastSeenCommit     string
	ParsedAt           string
	FeatureName        string
	FeatureDescription *string
	FeatureVersion     string
	RawContent         *string
	Requirements       string
	InsertedAt         string
	UpdatedAt          string
}

// Returns the inserted/updated spec row. The `xmax` trick used in Postgres
// doesn't work in SQLite; we use the changes() function indirectly by checking
// whether the row existed before. Caller decides created-vs-updated.
func (q *Queries) UpsertSpec(ctx context.Context, arg UpsertSpecParams) (Spec, error) {
	row := q.db.QueryRowContext(ctx, upsertSpec,
		arg.ID,
		arg.ProductID,
		arg.BranchID,
		arg.Path,
		arg.LastSeenCommit,
		arg.ParsedAt,
		arg.FeatureName,
		arg.FeatureDescription,
		arg.FeatureVersion,
		arg.RawContent,
		arg.Requirements,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.Path,
		&i.LastSeenCommit,
		&i.ParsedAt,
		&i.FeatureName,
		&i.FeatureDescription,
		&i.FeatureVersion,
		&i.RawContent,
		&i.Requirements,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrackedBranch = `-- name: UpsertTrackedBranch :exec
INSERT INTO tracked_branches (implementation_id, branch_id, repo_uri, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(implementation_id, branch_id) DO NOTHING
`

type UpsertTrackedBranchParams struct {
	ImplementationID string
	BranchID         string
	RepoUri          string
	InsertedAt       string
	UpdatedAt        string
}

func (q *Queries) UpsertTrackedBranch(ctx context.Context, arg UpsertTrackedBranchParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackedBranch,
		arg.ImplementationID,
		arg.BranchID,
		arg.RepoUri,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	return err
}
