// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS one
`

// Ping returns 1 if the DB is reachable. Used by /_health.
func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var one int64
	err := row.Scan(&one)
	return one, err
}
