// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, global_admin, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, global_admin, inserted_at, updated_at
`

type CreateTeamParams struct {
	ID          string
	Name        string
	GlobalAdmin int64
	InsertedAt  string
	UpdatedAt   string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.GlobalAdmin,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GlobalAdmin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserTeamRole = `-- name: CreateUserTeamRole :exec
INSERT INTO user_team_roles (team_id, user_id, title, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserTeamRoleParams struct {
	TeamID     string
	UserID     string
	Title      string
	InsertedAt string
	UpdatedAt  string
}

func (q *Queries) CreateUserTeamRole(ctx context.Context, arg CreateUserTeamRoleParams) error {
	_, err := q.db.ExecContext(ctx, createUserTeamRole,
		arg.TeamID,
		arg.UserID,
		arg.Title,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, global_admin, inserted_at, updated_at
FROM teams
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GlobalAdmin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.name, t.global_admin, t.inserted_at, t.updated_at
FROM teams t
JOIN user_team_roles utr ON utr.team_id = t.id
WHERE utr.user_id = ?
ORDER BY t.name
`

func (q *Queries) ListTeamsForUser(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GlobalAdmin,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
