// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, global_admin, inserted_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, global_admin, inserted_at, updated_at
`

type CreateTeamParams struct {
	ID          string
	Name        string
	GlobalAdmin int64
	InsertedAt  string
	UpdatedAt   string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.GlobalAdmin,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GlobalAdmin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, global_admin, inserted_at, updated_at
FROM teams
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GlobalAdmin,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
